version: '2'

services:
  glimpseCam:
    build:
      context: .
      dockerfile: ./Dockerfile
    privileged: true
    ports: 
      - "3000:3000"
    restart: always
    network_mode: "host"
    labels:
      io.balena.features.kernel-modules: '1'
